### ISSUE TITLE
Extending job name formatting for parameter names and values

### ISSUE THREAD

**Issue by jtcramer** [beasteers/slurmjobs#4]
There are two common issues I run into that would be cool to address here:

**1) Parameter names can get super long, especially when there's lots of varaibles.**
One way I deal with this is by abbreviating parameter names. Can be addressed by an appropriate format via #3, with something like `job_name_tpl = '_'.join(f'{"".join(f"{y:.{max_abbr_len}}" for y in param_name.split(f"{param_part_delimiter}"))}-{{{_obliterate_special(name)}}}' for name in param_names)` (e.g. a parameter with name `asdf_qwer_zxcv` becomes `asqwzx` with `max_abbr_len=2` and `param_part_delimiter="_"`), but there are probably better ways to do this. This also requires checking for collisions between abbreviated parameter names.

**2) Parameter values can get long and obfuscated, especially for floating point values**
Technically this could be addressed by #3, but it'd be nice to have a global way of setting it without having to make your own format string. For floats I usually do `f"{v:.{precision}e}"`, but also scientific notation isn't the best representation for all float parameters. So I'm not sure what the most elegant way is to be able to specify data type formats from parameter specific formats.

**Comment by beasteers** [comment]
> This also requires checking for collisions between abbreviated parameter names.

I was thinking about it and I don't know if we actually NEED to check for abbreviations (other than for reasons of clarity), assuming we have consistently ordered parameters.

**Comment by beasteers** [comment]
This is now easy with `slurmjobs>1.0.0`!! 

just override these methods to customize:

https://github.com/beasteers/slurmjobs/blob/f48c9a42da4e8e66b05648e6827d5b2d4180910a/slurmjobs/core.py#L148-L208

or use the in-built customization and change these parameters:

https://github.com/beasteers/slurmjobs/blob/f48c9a42da4e8e66b05648e6827d5b2d4180910a/slurmjobs/core.py#L69-L78

for example you could do:

```python
import slurmjobs

class Sing(slurmjobs.Singularity):
    # define some aliases
    key_abbreviations = {"batch_size": "bs", "epochs": "E"}
    # limit decimal places
    float_precision = 3

    # handle a certain type differently
    def format_id_item(self, key,  value):
        if isinstance(value, dict): 
            value = ','.join(f'{k}:{v}' for k, v in value.items())
            return f"{key}-{value}"
        return super().format_id_item()

    # or override the entire job ID - as an example, you could hash the job id? idk lol 
    # or just do an entirely different thing
    def format_job_id(self, *a, **kw):
        job_id = super().format_job_id(*a, **kw)
        return some_special_hash_function(job_id, n_chars=8)
```

**Comment by beasteers** [comment]
but @auroracramer lmk if you have additional thoughts about how to make this even more convenient!
